### ISSUE TITLE
failure on startup, loading via jar

### ISSUE THREAD

**Issue by rogerallen** [rogerallen/geemee#2]
When the page is first opened, there is a failure.  This is the console log

```
core.cljs?rel=1469717483206:75 Loading: gamma.api cljs
core.cljs?rel=1469717483206:75 Loading: gamma.ast cljs
```

UPDATE: The first call fails here because the `uate` routine returns an `:error` with: `Namespace "gamma.ast" already declared.`

```
core.cljs:150 #object[TypeError TypeError: Cannot read property 'call' of null]
core.cljs:150 Error rgb-fn nil
utils.cljs?rel=1469714821272:49 Figwheel: trying to open cljs reload socket
utils.cljs?rel=1469714821272:49 Figwheel: socket connection established
```

Clicking the "update" button  causes another recompile and it works.  For example...

```
core.cljs?rel=1469717483206:75 Loading: gamma.api cljs
core.cljs?rel=1469717483206:75 Loading: gamma.ast cljs
core.cljs?rel=1469717483206:75 Loading: gamma.api clj
```

The difference appears to be a load of gamma.api clj, but needs more investigation...

**Comment by rogerallen** [comment]
The first call fails because the uate routine fails with: `Namespace "gamma.ast" already declared.`

**Comment by rogerallen** [comment]
```
> lein do clean, cljsbuild once min
...
> python -m http.server
```

shows a different issue:

```
geemee.js:2693 after-load
geemee.js:2693 not init
geemee.js:2693 uate
geemee.js:2700 Loading: gamma.api cljs
geemee.js:2700 Loading: gamma.ast cljs
geemee.js:2693 evaluate error: Cannot read property 'kd' of null at line 6 
'''
```

**Comment by rogerallen** [comment]
okay, I've got a stack trace...

```
Update
Evaluation error: Error: Namespace "gamma.ast" already declared.
    at Error (native)
    at Object.goog.provide (http://localhost:3449/js/compiled/out/goog/base.js:273:13)
    at eval (eval at cljs$js$js_eval (http://localhost:3449/js/compiled/out/cljs/js.js:131:13), :1:6)
    at cljs$js$js_eval (http://localhost:3449/js/compiled/out/cljs/js.js:131:8)
    at http://localhost:3449/js/compiled/out/cljs/js.js:1672:215
    at http://localhost:3449/js/compiled/out/cljs/js.js:1675:4
    at cljs$js$eval_str_STAR__$_compile_loop (http://localhost:3449/js/compiled/out/cljs/js.js:1685:17)
    at http://localhost:3449/js/compiled/out/cljs/js.js:1625:46
    at http://localhost:3449/js/compiled/out/cljs/js.js:797:11
    at cljs$js$load_macros (http://localhost:3449/js/compiled/out/cljs/js.js:670:11)
    at http://localhost:3449/js/compiled/out/cljs/js.js:775:28
    at cljs$js$load_macros (http://localhost:3449/js/compiled/out/cljs/js.js:670:11)
    at cljs$js$check_uses_and_load_macros (http://localhost:3449/js/compiled/out/cljs/js.js:765:28)
    at Function.cljs.js.ns_side_effects.cljs$core$IFn$_invoke$arity$6 (http://localhost:3449/js/compiled/out/cljs/js.js:835:35)
    at cljs$js$ns_side_effects (http://localhost:3449/js/compiled/out/cljs/js.js:696:32)
    at cljs$js$eval_str_STAR__$_compile_loop (http://localhost:3449/js/compiled/out/cljs/js.js:1620:32)
    at cljs$js$eval_str_STAR_ (http://localhost:3449/js/compiled/out/cljs/js.js:1709:2)
    at http://localhost:3449/js/compiled/out/cljs/js.js:390:31
    at geemee$core$loader (http://localhost:3449/js/compiled/out/geemee/core.js:101:17)
    at Function.cljs.js.require.cljs$core$IFn$_invoke$arity$5 (http://localhost:3449/js/compiled/out/cljs/js.js:373:121)
    at cljs$js$require (http://localhost:3449/js/compiled/out/cljs/js.js:314:24)
    at Function.cljs.js.require.cljs$core$IFn$_invoke$arity$4 (http://localhost:3449/js/compiled/out/cljs/js.js:332:24)
    at cljs$js$require (http://localhost:3449/js/compiled/out/cljs/js.js:310:24)
    at Function.cljs.js.load_deps.cljs$core$IFn$_invoke$arity$6 (http://localhost:3449/js/compiled/out/cljs/js.js:515:24)
    at cljs$js$load_deps (http://localhost:3449/js/compiled/out/cljs/js.js:482:26)
    at Function.cljs.js.ns_side_effects.cljs$core$IFn$_invoke$arity$6 (http://localhost:3449/js/compiled/out/cljs/js.js:819:26)
    at cljs$js$ns_side_effects (http://localhost:3449/js/compiled/out/cljs/js.js:696:32)
    at cljs$js$eval_str_STAR__$_compile_loop (http://localhost:3449/js/compiled/out/cljs/js.js:1620:32)
    at cljs$js$eval_str_STAR_ (http://localhost:3449/js/compiled/out/cljs/js.js:1709:2)
    at http://localhost:3449/js/compiled/out/cljs/js.js:390:31
    at geemee$core$loader (http://localhost:3449/js/compiled/out/geemee/core.js:101:17)
    at Function.cljs.js.require.cljs$core$IFn$_invoke$arity$5 (http://localhost:3449/js/compiled/out/cljs/js.js:373:121)
    at cljs$js$require (http://localhost:3449/js/compiled/out/cljs/js.js:314:24)
    at Function.cljs.js.require.cljs$core$IFn$_invoke$arity$4 (http://localhost:3449/js/compiled/out/cljs/js.js:332:24)
    at cljs$js$require (http://localhost:3449/js/compiled/out/cljs/js.js:310:24)
    at Function.cljs.js.load_deps.cljs$core$IFn$_invoke$arity$6 (http://localhost:3449/js/compiled/out/cljs/js.js:515:24)
    at cljs$js$load_deps (http://localhost:3449/js/compiled/out/cljs/js.js:482:26)
    at Function.cljs.js.ns_side_effects.cljs$core$IFn$_invoke$arity$6 (http://localhost:3449/js/compiled/out/cljs/js.js:819:26)
    at cljs$js$ns_side_effects (http://localhost:3449/js/compiled/out/cljs/js.js:696:32)
    at cljs$js$eval_str_STAR__$_compile_loop (http://localhost:3449/js/compiled/out/cljs/js.js:1620:32)
    at cljs$js$eval_str_STAR_ (http://localhost:3449/js/compiled/out/cljs/js.js:1709:2)
    at Function.cljs.js.eval_str.cljs$core$IFn$_invoke$arity$5 (http://localhost:3449/js/compiled/out/cljs/js.js:1812:31)
    at cljs$js$eval_str (http://localhost:3449/js/compiled/out/cljs/js.js:1769:25)
    at geemee$core$uate (http://localhost:3449/js/compiled/out/geemee/core.js:118:25)
    at geemee$core$get_rgb_fn (http://localhost:3449/js/compiled/out/geemee/core.js:142:31)
    at geemee$core$init (http://localhost:3449/js/compiled/out/geemee/core.js:158:280)
    at geemee$core$draw_new_image (http://localhost:3449/js/compiled/out/geemee/core.js:222:18)
    at geemee$core$after_load (http://localhost:3449/js/compiled/out/geemee/core.js:242:35)
    at http://localhost:3449/js/compiled/out/geemee/core.js:245:40
```

**Comment by rogerallen** [comment]
I can work around the startup issue by just loading some non-evaluated shader code.  But that only works when running `lein figwheel`.  If i do a `lein do clean, cljsbuild once` (drop `min` from commandline, then it always fails just like the stacktrace above.  (the 'kd' = null error is due to minification of js, I guess?)

So, this is a showstopper for deploying as static website.

**Comment by rogerallen** [comment]
Here is the stack comparison of the good vs. bad stack trace.

![image](https://cloud.githubusercontent.com/assets/1237285/17278040/101137b6-5707-11e6-8a0e-d7276b5dd9fa.png)

**Comment by rogerallen** [comment]
Okay, now I'm getting somewhere.  In the error case, stepping though the code, I get to a place where it tries to figure out if the namespace is provided.

```
goog.provide = function(name) {
  if (!COMPILED) {
    // Ensure that the same namespace isn't provided twice.
    // A goog.module/goog.provide maps a goog.require to a specific file
    if (goog.isProvided_(name)) {
      throw Error('Namespace "' + name + '" already declared.');
    }
  }

  goog.constructNamespace_(name);
};
```

The bad case actually steps into the actual google function goog.isProvided() which fails due to the error above.

However, the good case steps into a figwheel override inside figwheel/client/file_reloading.cljs

```
(defn bootstrap-goog-base
  "Reusable browser REPL bootstrapping. Patches the essential functions
  in goog.base to support re-loading of namespaces after page load."
  []
  ;; The biggest problem here is that clojure.browser.repl might have
  ;; patched this or might patch this afterward
  (when-not js/COMPILED
    ;; 
    (set! (.-require_figwheel_backup_ js/goog) (or js/goog.require__ js/goog.require))
    ;; suppress useless Google Closure error about duplicate provides
    (set! (.-isProvided_ js/goog) (fn [name] false))
    ;; provide cljs.user
    (setup-path->name!)
    (setup-ns->dependents!)
...
```

Notice the 
**;; suppress useless Google Closure error about duplicate provides
(set! (.-isProvided_ js/goog) (fn [name] false))**

That's an interesting find!

**Comment by rogerallen** [comment]
Hah!  adding that code "fixes" the problem!

**Comment by rogerallen** [comment]
Almost fixes.  

`lein do clean, cljsbuild once` works
`lein do clean, cljsbuild once min` fails

I suppose the name is not js/goog/.-isProvided? It is some minified version?  Hmm...

**Comment by rogerallen** [comment]
Only :none and :simple optimizations are supported for bootstrapped ClojureScript.
see https://github.com/clojure/clojurescript/wiki/Compiler-Options

adjusting that setting & now we're good.  closing.
